name: reso_coder_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  oauth2: ^2.0.0
  flutter_secure_storage: ^5.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  webview_flutter: ^3.0.4
  flash: ^2.0.3+2
  auto_route: ^4.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_riverpod: ^1.0.4
  riverpod: ^1.0.3
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  lint: ^1.8.2
  auto_route_generator: ^4.0.0
  
flutter:
  uses-material-design: true

